- name: gather facts kafka-server
  hosts: kafka-server
  sudo: yes
  gather_facts: yes
  remote_user: ubuntu
  tasks:
    set_up:

- hosts: all
  sudo: yes
  gather_facts: yes
  remote_user: ubuntu
  roles:
    - install
    - plugin
    - kick-start
  vars:
    tdagent_plugins:
      - fluent-plugin-extract_query_params
      - fluent-plugin-s3
      - fluent-plugin-kafka
