- name: back-up previous td-agent.conf
  command: creates="/etc/td-agent/td-agent.conf.bak" mv /etc/td-agent/td-agent.conf /etc/td-agent/td-agent.conf.bak

- name: copy new td-agent.conf from role's default
  template: src=td-agent.j2  dest=/etc/td-agent/td-agent.conf
  notify:
    - restart td-agent
